apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  labels:
    app: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: web-server
        image: nginx
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c", "echo $(DATA_STRING) > $(DATA_PATH); sleep 5000"  ]
        env:
        - name: DATA_STRING
          valueFrom:
            configMapKeyRef:
              name: web-conf
              key: STRING
              optional: true
        - name: DATA_PATH
          valueFrom:
            configMapKeyRef:
              name: web-conf
              key: PATH
              optional: true
  restartPolicy: Never



      
         