apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-vpn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        ports:
        - containerPort: 51820
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"