apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-vpn
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 51820
# Env's from cfg-map        
        env:
        - name: USER-ID
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: PUID
              optional: true
          
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: TZ
              optional: true

        - name: GROUP-ID
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: PGID
              optional: true

        - name: SERVER-URL
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: SERVERURL
              optional: true

        - name: SERVER-PORT
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: SERVERPORT
              optional: true

        - name: VPN-PEERS
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: PEERS
              optional: true

        - name: PEER-DNS
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: PEERDNS
              optional: true

        - name: INTERNAL-SUBNET
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: INTERNAL_SUBNET
              optional: true

        - name: ALLOW-IP
          valueFrom:
            configMapKeyRef:
            name: wireguard-conf
            key: ALLOWEDIPS 
            optional: true            

        - name: RUN-OPTS
          valueFrom:
            configMapKeyRef:
              name: wireguard-conf
              key: run-opts
              optional: true

# Volume Mounts 
        volumeMounts:
          - name: config
            mountPath: /var/wireguard/config
          - name: modules
            mountPath: /lib/modules 
# ressource-limits     
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"