apiVersion: v1
kind: Service
metadata:
  name: wireguard-svc
  labels:
    app: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      port: 51820
      nodePort: 5050
