apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-conf
data:
# Env-Vars 
  PUID: "0"
  PGID: "0"
  TZ: "Europe/Berlin"
  SERVERURL: "homestation-ibra.ddns.net"
  SERVERPORT: "51820"
  PEERS: "5"
  PEERDNS: "auto"
  INTERNAL_SUBNET: "10.13.13.0"
  ALLOWEDIPS: "0.0.0.0/0"
#Options
  run-opts: |
    -cap-add=NET_ADMIN
    -cap-add=SYS_MODULE
    --sysctl="net.ipv4.conf.all.src_valid_mark=1"


  







