apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deploy
spec:
  selector:
    matchLabels:
      app: monitoring-deploy
  template:
    metadata:
      labels:
        app: monitoring-deploy
    spec:
      containers:
#prometheus
      - name: prometheus 
        image: bitnami/prometheus:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
          - containerPort: 9090

#grafana
      - name: grafana
        image: bitnami/grafana:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000

