apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-vol
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data